
language: c

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

#before_install:
#  - sudo apt-get install capstone -y

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. && make VERBOSE=1 && ctest --output-on-failure
